services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs 
      - ./vhost:/etc/nginx/vhost.d 
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
        - DEFAULT_EMAIL=porom.kamal@mail.utoronto.ca

  frontend:
    image: ghcr.io/uoft-utsc-cs-sandbox/stormai-frontend
    container_name: frontend
    expose:
      - 80
    restart: always
    environment:
      - VIRTUAL_HOST=stormai.live
      - LETSENCRYPT_HOST=stormai.live

  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: stormai
      POSTGRES_PASSWORD: stormai
    volumes:
        - postgres:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: stormai@stormai.com
      PGADMIN_DEFAULT_PASSWORD: stormai
    ports:
        - "5050:80"
  
  authserver:
    build:
      context: ./backend/SpringServer
      dockerfile: Dockerfile
    container_name: authservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stormai
    ports:
      - "5500:5500"
    depends_on:
        - postgres
    restart: always
  
  nodeserver:
    build:
      context: ./backend/NodeServer
      dockerfile: Dockerfile
    container_name: nodeserver
    ports:
      - "5000:5000"
    restart: always
  
  paymentserver:
    build:
      context: ./backend/PaymentServer
      dockerfile: Dockerfile
    container_name: paymentservice
    ports:
      - "3001:3001"
    restart: always
  
  roomserver:
    build:
      context: ./backend/RoomServer
      dockerfile: Dockerfile
    container_name: roomservice
    ports:
      - "5555:5555"
    restart: always
    depends_on:
      - mongodb_container

  signalingserver:
    build:
      context: ./backend/SignalingServer
      dockerfile: Dockerfile
    container_name: signalingserver
    ports:
      - "4444:4444"
    restart: always
  

