version: "3"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs 
      - ./vhost:/etc/nginx/vhost.d 
      - ./html:/usr/share/nginx/html
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
        - DEFAULT_EMAIL=porom.kamal@mail.utoronto.ca

  frontend:
    image: ghcr.io/uoft-utsc-cs-sandbox/stormai-frontend
    container_name: frontend
    expose:
      - 80
    restart: always
    environment:
      - VIRTUAL_HOST=stormai.live
      - LETSENCRYPT_HOST=stormai.live

  authserver:
    image: ghcr.io/uoft-utsc-cs-sandbox/stormai-auth-server
    container_name: authservice
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/stormai
      - VIRTUAL_HOST=auth.stormai.live
      - LETSENCRYPT_HOST=auth.stormai.live
    expose:
      - 5500
    depends_on:
        - postgres
    restart: always
    
  postgres:
    container_name: postgres
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: stormai
      POSTGRES_PASSWORD: stormai
    volumes:
        - /postgres:/var/lib/postgresql/data
    ports:
        - "5432:5432"
      
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_container:/data/db

  nodeserver:
    image: ghcr.io/uoft-utsc-cs-sandbox/stormai-node-server
    container_name: nodeserver
    environment:
      - VIRTUAL_HOST=node.stormai.live
      - LETSENCRYPT_HOST=node.stormai.live
    expose:
      - 5000
    restart: always
  
  paymentserver:
    image: ghcr.io/uoft-utsc-cs-sandbox/stormai-payment-server
    container_name: paymentservice
    environment:
      - VIRTUAL_HOST=payment.stormai.live
      - LETSENCRYPT_HOST=payment.stormai.live
    expose:
      - 3001
    restart: always
  
  roomserver:
    image: ghcr.io/uoft-utsc-cs-sandbox/stormai-room-server
    container_name: roomservice
    environment:
      - VIRTUAL_HOST=room.stormai.live
      - LETSENCRYPT_HOST=room.stormai.live
    expose:
      - 5555
    restart: always
    depends_on:
      - mongodb_container

  signalingserver:
    image: ghcr.io/uoft-utsc-cs-sandbox/stormai-signaling-server
    container_name: signalingserver
    expose:
      - 4444
    environment:
      - VIRTUAL_HOST=signaling.stormai.live
      - LETSENCRYPT_HOST=signaling.stormai.live
    restart: always
  