server:
  port: 5500

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: jtjcc2AbLWPOJNv6fpX6Y9G8p2xB85xB
            client-secret: insert_client_secret_here
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-476vq6rjyr7khvrn.us.auth0.com/
